/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/123-mod-apk': RouteRecordInfo<
      '/posts/123-mod-apk',
      '/posts/123-mod-apk',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/about': RouteRecordInfo<
      '/posts/about',
      '/posts/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Alexcraft-mc': RouteRecordInfo<
      '/posts/Alexcraft-mc',
      '/posts/Alexcraft-mc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bili-musci-Windows': RouteRecordInfo<
      '/posts/bili-musci-Windows',
      '/posts/bili-musci-Windows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bilibili-two': RouteRecordInfo<
      '/posts/bilibili-two',
      '/posts/bilibili-two',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/guanfang-qunzu': RouteRecordInfo<
      '/posts/guanfang-qunzu',
      '/posts/guanfang-qunzu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Java-download': RouteRecordInfo<
      '/posts/Java-download',
      '/posts/Java-download',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/make-up': RouteRecordInfo<
      '/posts/make-up',
      '/posts/make-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mao-mao-qi-yu-zhong-guo': RouteRecordInfo<
      '/posts/mao-mao-qi-yu-zhong-guo',
      '/posts/mao-mao-qi-yu-zhong-guo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/minecraftji-chu-lian-ji-jiao-chengyi': RouteRecordInfo<
      '/posts/minecraftji-chu-lian-ji-jiao-chengyi',
      '/posts/minecraftji-chu-lian-ji-jiao-chengyi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/minecraftjin-jie-jiao-cheng': RouteRecordInfo<
      '/posts/minecraftjin-jie-jiao-cheng',
      '/posts/minecraftjin-jie-jiao-cheng',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mo-ni-ren-sheng': RouteRecordInfo<
      '/posts/mo-ni-ren-sheng',
      '/posts/mo-ni-ren-sheng',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/modpack-one': RouteRecordInfo<
      '/posts/modpack-one',
      '/posts/modpack-one',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/PCL-CE-N': RouteRecordInfo<
      '/posts/PCL-CE-N',
      '/posts/PCL-CE-N',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/SakuraFrp-1': RouteRecordInfo<
      '/posts/SakuraFrp-1',
      '/posts/SakuraFrp-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yang-lao': RouteRecordInfo<
      '/posts/yang-lao',
      '/posts/yang-lao',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yi-kuan-bilibiliyin-le-bo-fang-qi': RouteRecordInfo<
      '/posts/yi-kuan-bilibiliyin-le-bo-fang-qi',
      '/posts/yi-kuan-bilibiliyin-le-bo-fang-qi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yi-kuan-mian-fei-yun-yin-le-bo-fang-qi': RouteRecordInfo<
      '/posts/yi-kuan-mian-fei-yun-yin-le-bo-fang-qi',
      '/posts/yi-kuan-mian-fei-yun-yin-le-bo-fang-qi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zhao-da-zi': RouteRecordInfo<
      '/posts/zhao-da-zi',
      '/posts/zhao-da-zi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zhe-li-hui-fa-bu-shi-me': RouteRecordInfo<
      '/posts/zhe-li-hui-fa-bu-shi-me',
      '/posts/zhe-li-hui-fa-bu-shi-me',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zhu-meng-wu-yu': RouteRecordInfo<
      '/posts/zhu-meng-wu-yu',
      '/posts/zhu-meng-wu-yu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    '../node_modules/.pnpm/valaxy-theme-sakura@0.10.2__ff83fa824efa1b010746f272c297a1c3/node_modules/valaxy-theme-sakura/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    '../node_modules/.pnpm/valaxy@1.0.0-rc.9_@babel+pa_fd30fd20dfe228c6347fc82435f6c1d5/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
      pathParamNames:
        | never
    }
    '../node_modules/.pnpm/valaxy-theme-sakura@0.10.2__ff83fa824efa1b010746f272c297a1c3/node_modules/valaxy-theme-sakura/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'pages/posts/123-mod-apk.md': {
      routes:
        | '/posts/123-mod-apk'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/about.md': {
      routes:
        | '/posts/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Alexcraft-mc.md': {
      routes:
        | '/posts/Alexcraft-mc'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/bili-musci-Windows.md': {
      routes:
        | '/posts/bili-musci-Windows'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/bilibili-two.md': {
      routes:
        | '/posts/bilibili-two'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/guanfang-qunzu.md': {
      routes:
        | '/posts/guanfang-qunzu'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Java-download.md': {
      routes:
        | '/posts/Java-download'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/make-up.md': {
      routes:
        | '/posts/make-up'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/mao-mao-qi-yu-zhong-guo.md': {
      routes:
        | '/posts/mao-mao-qi-yu-zhong-guo'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/minecraftji-chu-lian-ji-jiao-chengyi.md': {
      routes:
        | '/posts/minecraftji-chu-lian-ji-jiao-chengyi'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/minecraftjin-jie-jiao-cheng.md': {
      routes:
        | '/posts/minecraftjin-jie-jiao-cheng'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/mo-ni-ren-sheng.md': {
      routes:
        | '/posts/mo-ni-ren-sheng'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/modpack-one.md': {
      routes:
        | '/posts/modpack-one'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/PCL-CE-N.md': {
      routes:
        | '/posts/PCL-CE-N'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/SakuraFrp-1.md': {
      routes:
        | '/posts/SakuraFrp-1'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/yang-lao.md': {
      routes:
        | '/posts/yang-lao'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/yi-kuan-bilibiliyin-le-bo-fang-qi.md': {
      routes:
        | '/posts/yi-kuan-bilibiliyin-le-bo-fang-qi'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/yi-kuan-mian-fei-yun-yin-le-bo-fang-qi.md': {
      routes:
        | '/posts/yi-kuan-mian-fei-yun-yin-le-bo-fang-qi'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/zhao-da-zi.md': {
      routes:
        | '/posts/zhao-da-zi'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/zhe-li-hui-fa-bu-shi-me.md': {
      routes:
        | '/posts/zhe-li-hui-fa-bu-shi-me'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/zhu-meng-wu-yu.md': {
      routes:
        | '/posts/zhu-meng-wu-yu'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
