/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/comments/': RouteRecordInfo<
      '/comments/',
      '/comments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/friends': RouteRecordInfo<
      '/friends',
      '/friends',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/games': RouteRecordInfo<
      '/games',
      '/games',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/list': RouteRecordInfo<
      '/list',
      '/list',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/movies': RouteRecordInfo<
      '/movies',
      '/movies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/playlists': RouteRecordInfo<
      '/playlists',
      '/playlists',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/123-mod-apk': RouteRecordInfo<
      '/posts/123-mod-apk',
      '/posts/123-mod-apk',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/about': RouteRecordInfo<
      '/posts/about',
      '/posts/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/akdy': RouteRecordInfo<
      '/posts/akdy',
      '/posts/akdy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Alexcraft-mc': RouteRecordInfo<
      '/posts/Alexcraft-mc',
      '/posts/Alexcraft-mc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/aysykj': RouteRecordInfo<
      '/posts/aysykj',
      '/posts/aysykj',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bili-musci-Windows': RouteRecordInfo<
      '/posts/bili-musci-Windows',
      '/posts/bili-musci-Windows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/bilibili-two': RouteRecordInfo<
      '/posts/bilibili-two',
      '/posts/bilibili-two',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Blood-curse': RouteRecordInfo<
      '/posts/Blood-curse',
      '/posts/Blood-curse',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CC5': RouteRecordInfo<
      '/posts/CC5',
      '/posts/CC5',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CCCP-su': RouteRecordInfo<
      '/posts/CCCP-su',
      '/posts/CCCP-su',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/CiscoRPG': RouteRecordInfo<
      '/posts/CiscoRPG',
      '/posts/CiscoRPG',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/cjzd': RouteRecordInfo<
      '/posts/cjzd',
      '/posts/cjzd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Crashed': RouteRecordInfo<
      '/posts/Crashed',
      '/posts/Crashed',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/db': RouteRecordInfo<
      '/posts/db',
      '/posts/db',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/DHdlyz': RouteRecordInfo<
      '/posts/DHdlyz',
      '/posts/DHdlyz',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/djywl': RouteRecordInfo<
      '/posts/djywl',
      '/posts/djywl',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/dxjb': RouteRecordInfo<
      '/posts/dxjb',
      '/posts/dxjb',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/feituzhixia': RouteRecordInfo<
      '/posts/feituzhixia',
      '/posts/feituzhixia',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/fkm': RouteRecordInfo<
      '/posts/fkm',
      '/posts/fkm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/fkxj': RouteRecordInfo<
      '/posts/fkxj',
      '/posts/fkxj',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/fmbj': RouteRecordInfo<
      '/posts/fmbj',
      '/posts/fmbj',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/FZZL2.0': RouteRecordInfo<
      '/posts/FZZL2.0',
      '/posts/FZZL2/0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/guanfang-qunzu': RouteRecordInfo<
      '/posts/guanfang-qunzu',
      '/posts/guanfang-qunzu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hdt': RouteRecordInfo<
      '/posts/hdt',
      '/posts/hdt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hzqsl': RouteRecordInfo<
      '/posts/hzqsl',
      '/posts/hzqsl',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Java': RouteRecordInfo<
      '/posts/Java',
      '/posts/Java',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Java-download': RouteRecordInfo<
      '/posts/Java-download',
      '/posts/Java-download',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/jhjy': RouteRecordInfo<
      '/posts/jhjy',
      '/posts/jhjy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/jsxt': RouteRecordInfo<
      '/posts/jsxt',
      '/posts/jsxt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/kb': RouteRecordInfo<
      '/posts/kb',
      '/posts/kb',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/lcylc': RouteRecordInfo<
      '/posts/lcylc',
      '/posts/lcylc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/liesha': RouteRecordInfo<
      '/posts/liesha',
      '/posts/liesha',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/lyzp': RouteRecordInfo<
      '/posts/lyzp',
      '/posts/lyzp',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/M-F-yy': RouteRecordInfo<
      '/posts/M-F-yy',
      '/posts/M-F-yy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/make-up': RouteRecordInfo<
      '/posts/make-up',
      '/posts/make-up',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mao-mao-qi-yu-zhong-guo': RouteRecordInfo<
      '/posts/mao-mao-qi-yu-zhong-guo',
      '/posts/mao-mao-qi-yu-zhong-guo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/minecraftji-chu-lian-ji-jiao-chengyi': RouteRecordInfo<
      '/posts/minecraftji-chu-lian-ji-jiao-chengyi',
      '/posts/minecraftji-chu-lian-ji-jiao-chengyi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/minecraftjin-jie-jiao-cheng': RouteRecordInfo<
      '/posts/minecraftjin-jie-jiao-cheng',
      '/posts/minecraftjin-jie-jiao-cheng',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mndds': RouteRecordInfo<
      '/posts/mndds',
      '/posts/mndds',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mo-ni-ren-sheng': RouteRecordInfo<
      '/posts/mo-ni-ren-sheng',
      '/posts/mo-ni-ren-sheng',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/modpack-one': RouteRecordInfo<
      '/posts/modpack-one',
      '/posts/modpack-one',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mwnz': RouteRecordInfo<
      '/posts/mwnz',
      '/posts/mwnz',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mznl': RouteRecordInfo<
      '/posts/mznl',
      '/posts/mznl',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/newage': RouteRecordInfo<
      '/posts/newage',
      '/posts/newage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/niepan': RouteRecordInfo<
      '/posts/niepan',
      '/posts/niepan',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/OB': RouteRecordInfo<
      '/posts/OB',
      '/posts/OB',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/PCL-CE-N': RouteRecordInfo<
      '/posts/PCL-CE-N',
      '/posts/PCL-CE-N',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/pxzj2.0': RouteRecordInfo<
      '/posts/pxzj2.0',
      '/posts/pxzj2/0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/QA': RouteRecordInfo<
      '/posts/QA',
      '/posts/QA',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/qq': RouteRecordInfo<
      '/posts/qq',
      '/posts/qq',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/qunluanjy': RouteRecordInfo<
      '/posts/qunluanjy',
      '/posts/qunluanjy',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/quweibao': RouteRecordInfo<
      '/posts/quweibao',
      '/posts/quweibao',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/RSmx': RouteRecordInfo<
      '/posts/RSmx',
      '/posts/RSmx',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/SakuraFrp-1': RouteRecordInfo<
      '/posts/SakuraFrp-1',
      '/posts/SakuraFrp-1',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/shdmx': RouteRecordInfo<
      '/posts/shdmx',
      '/posts/shdmx',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/thelastday': RouteRecordInfo<
      '/posts/thelastday',
      '/posts/thelastday',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/wrrm': RouteRecordInfo<
      '/posts/wrrm',
      '/posts/wrrm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/wxzz': RouteRecordInfo<
      '/posts/wxzz',
      '/posts/wxzz',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/xgcz': RouteRecordInfo<
      '/posts/xgcz',
      '/posts/xgcz',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yang-lao': RouteRecordInfo<
      '/posts/yang-lao',
      '/posts/yang-lao',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yhxw': RouteRecordInfo<
      '/posts/yhxw',
      '/posts/yhxw',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yi-kuan-bilibiliyin-le-bo-fang-qi': RouteRecordInfo<
      '/posts/yi-kuan-bilibiliyin-le-bo-fang-qi',
      '/posts/yi-kuan-bilibiliyin-le-bo-fang-qi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yi-kuan-mian-fei-yun-yin-le-bo-fang-qi': RouteRecordInfo<
      '/posts/yi-kuan-mian-fei-yun-yin-le-bo-fang-qi',
      '/posts/yi-kuan-mian-fei-yun-yin-le-bo-fang-qi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yj': RouteRecordInfo<
      '/posts/yj',
      '/posts/yj',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yqbns': RouteRecordInfo<
      '/posts/yqbns',
      '/posts/yqbns',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ysjx': RouteRecordInfo<
      '/posts/ysjx',
      '/posts/ysjx',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/yuanli': RouteRecordInfo<
      '/posts/yuanli',
      '/posts/yuanli',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ZG-RPG': RouteRecordInfo<
      '/posts/ZG-RPG',
      '/posts/ZG-RPG',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zhao-da-zi': RouteRecordInfo<
      '/posts/zhao-da-zi',
      '/posts/zhao-da-zi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zhe-li-hui-fa-bu-shi-me': RouteRecordInfo<
      '/posts/zhe-li-hui-fa-bu-shi-me',
      '/posts/zhe-li-hui-fa-bu-shi-me',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zhu-meng-wu-yu': RouteRecordInfo<
      '/posts/zhu-meng-wu-yu',
      '/posts/zhu-meng-wu-yu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zlsf': RouteRecordInfo<
      '/posts/zlsf',
      '/posts/zlsf',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zy2': RouteRecordInfo<
      '/posts/zy2',
      '/posts/zy2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/zzyh': RouteRecordInfo<
      '/posts/zzyh',
      '/posts/zzyh',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/search/': RouteRecordInfo<
      '/search/',
      '/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/valaxy-theme-sakura/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/comments/index.md': {
      routes:
        | '/comments/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/friends.md': {
      routes:
        | '/friends'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/games.md': {
      routes:
        | '/games'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/list.md': {
      routes:
        | '/list'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/movies.md': {
      routes:
        | '/movies'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
      pathParamNames:
        | 'page'
    }
    'pages/playlists.md': {
      routes:
        | '/playlists'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/123-mod-apk.md': {
      routes:
        | '/posts/123-mod-apk'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/about.md': {
      routes:
        | '/posts/about'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/akdy.md': {
      routes:
        | '/posts/akdy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Alexcraft-mc.md': {
      routes:
        | '/posts/Alexcraft-mc'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/aysykj.md': {
      routes:
        | '/posts/aysykj'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/bili-musci-Windows.md': {
      routes:
        | '/posts/bili-musci-Windows'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/bilibili-two.md': {
      routes:
        | '/posts/bilibili-two'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Blood-curse.md': {
      routes:
        | '/posts/Blood-curse'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CC5.md': {
      routes:
        | '/posts/CC5'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CCCP-su.md': {
      routes:
        | '/posts/CCCP-su'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/CiscoRPG.md': {
      routes:
        | '/posts/CiscoRPG'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/cjzd.md': {
      routes:
        | '/posts/cjzd'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Crashed.md': {
      routes:
        | '/posts/Crashed'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/db.md': {
      routes:
        | '/posts/db'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/DHdlyz.md': {
      routes:
        | '/posts/DHdlyz'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/djywl.md': {
      routes:
        | '/posts/djywl'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/dxjb.md': {
      routes:
        | '/posts/dxjb'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/feituzhixia.md': {
      routes:
        | '/posts/feituzhixia'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/fkm.md': {
      routes:
        | '/posts/fkm'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/fkxj.md': {
      routes:
        | '/posts/fkxj'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/fmbj.md': {
      routes:
        | '/posts/fmbj'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/FZZL2.0.md': {
      routes:
        | '/posts/FZZL2.0'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/guanfang-qunzu.md': {
      routes:
        | '/posts/guanfang-qunzu'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/hdt.md': {
      routes:
        | '/posts/hdt'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/hzqsl.md': {
      routes:
        | '/posts/hzqsl'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Java.md': {
      routes:
        | '/posts/Java'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/Java-download.md': {
      routes:
        | '/posts/Java-download'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/jhjy.md': {
      routes:
        | '/posts/jhjy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/jsxt.md': {
      routes:
        | '/posts/jsxt'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/kb.md': {
      routes:
        | '/posts/kb'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/lcylc.md': {
      routes:
        | '/posts/lcylc'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/liesha.md': {
      routes:
        | '/posts/liesha'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/lyzp.md': {
      routes:
        | '/posts/lyzp'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/M-F-yy.md': {
      routes:
        | '/posts/M-F-yy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/make-up.md': {
      routes:
        | '/posts/make-up'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/mao-mao-qi-yu-zhong-guo.md': {
      routes:
        | '/posts/mao-mao-qi-yu-zhong-guo'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/minecraftji-chu-lian-ji-jiao-chengyi.md': {
      routes:
        | '/posts/minecraftji-chu-lian-ji-jiao-chengyi'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/minecraftjin-jie-jiao-cheng.md': {
      routes:
        | '/posts/minecraftjin-jie-jiao-cheng'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/mndds.md': {
      routes:
        | '/posts/mndds'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/mo-ni-ren-sheng.md': {
      routes:
        | '/posts/mo-ni-ren-sheng'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/modpack-one.md': {
      routes:
        | '/posts/modpack-one'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/mwnz.md': {
      routes:
        | '/posts/mwnz'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/mznl.md': {
      routes:
        | '/posts/mznl'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/newage.md': {
      routes:
        | '/posts/newage'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/niepan.md': {
      routes:
        | '/posts/niepan'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/OB.md': {
      routes:
        | '/posts/OB'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/PCL-CE-N.md': {
      routes:
        | '/posts/PCL-CE-N'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/pxzj2.0.md': {
      routes:
        | '/posts/pxzj2.0'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/QA.md': {
      routes:
        | '/posts/QA'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/qq.md': {
      routes:
        | '/posts/qq'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/qunluanjy.md': {
      routes:
        | '/posts/qunluanjy'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/quweibao.md': {
      routes:
        | '/posts/quweibao'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/RSmx.md': {
      routes:
        | '/posts/RSmx'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/SakuraFrp-1.md': {
      routes:
        | '/posts/SakuraFrp-1'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/shdmx.md': {
      routes:
        | '/posts/shdmx'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/thelastday.md': {
      routes:
        | '/posts/thelastday'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/wrrm.md': {
      routes:
        | '/posts/wrrm'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/wxzz.md': {
      routes:
        | '/posts/wxzz'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/xgcz.md': {
      routes:
        | '/posts/xgcz'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/yang-lao.md': {
      routes:
        | '/posts/yang-lao'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/yhxw.md': {
      routes:
        | '/posts/yhxw'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/yi-kuan-bilibiliyin-le-bo-fang-qi.md': {
      routes:
        | '/posts/yi-kuan-bilibiliyin-le-bo-fang-qi'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/yi-kuan-mian-fei-yun-yin-le-bo-fang-qi.md': {
      routes:
        | '/posts/yi-kuan-mian-fei-yun-yin-le-bo-fang-qi'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/yj.md': {
      routes:
        | '/posts/yj'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/yqbns.md': {
      routes:
        | '/posts/yqbns'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/ysjx.md': {
      routes:
        | '/posts/ysjx'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/yuanli.md': {
      routes:
        | '/posts/yuanli'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/ZG-RPG.md': {
      routes:
        | '/posts/ZG-RPG'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/zhao-da-zi.md': {
      routes:
        | '/posts/zhao-da-zi'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/zhe-li-hui-fa-bu-shi-me.md': {
      routes:
        | '/posts/zhe-li-hui-fa-bu-shi-me'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/zhu-meng-wu-yu.md': {
      routes:
        | '/posts/zhu-meng-wu-yu'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/zlsf.md': {
      routes:
        | '/posts/zlsf'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/zy2.md': {
      routes:
        | '/posts/zy2'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/zzyh.md': {
      routes:
        | '/posts/zzyh'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/search/index.md': {
      routes:
        | '/search/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
